name: Deploy Lambda Function

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
jobs:

  deploy_zip:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build binary
        run: |
          cd write-payload-func && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip write-payload-func.zip main
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: write-payload-func
          zip_file: write-payload-func.zip
          memory_size: 128
          timeout: 10
          runtime: nodejs18.x