name: Deploy lambda write-payload-func

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy lambda
    runs-on: ubuntu-latest
    permissions: write-all
    env: 
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - name: Login to Vultr Instance and deploy lambda
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VULTR_INSTANCE_IP }}
          username: ${{ secrets.VULTR_INSTANCE_USER }}
          key: ${{ secrets.VULTR_INSTANCE_KEY }}
          script: |
            cd cloudwatch-mock
            [ -e write-payload-func.zip ] && rm write-payload-func.zip
            [ -e write_payload_func.zip ] && rm write_payload_func.zip
            git pull
            git stash
            curl -L -o write-payload-func.zip https://github.com/TudorIonutElian/write-payload-func/archive/refs/heads/main.zip
            unzip write-payload-func.zip -d write-payload-func

            mv write-payload-func/write-payload-func-main/* write-payload-func/
            rm -r write-payload-func/write-payload-func-main
            rm write-payload-func.zip

            cd write-payload-func
            npm install
            cd ../
            zip -r write-payload-func.zip write-payload-func
            aws lambda update-function-code --function-name write-payload-func --zip-file fileb://write-payload-func.zip

            

